opcodes = {
    0x0: ('playfram', 'H', ['frame'], 'Displays a particular frame, adjusted for direction.'),
    0x1: ('playframtile', 'H', ['frame'], 'Displays a particular frame dependent on tileset.'),
    0x2: ('sethorpos', 'B', ['x'], 'Sets the current horizontal offset of the current image overlay.'),
    0x3: ('setvertpos', 'B', ['y'], 'Sets the vertical position of an image overlay.'),
    0x4: ('setpos', 'BB', ['x', 'y'], 'Sets the current horizontal and vertical position of the current image overlay.'),
    0x5: ('wait', 'B', ['gameticks'], 'Pauses script execution for a specific number of ticks.'),
    0x6: ('waitrand', 'BB', ['gameticks1', 'gameticks2'], 'Pauses script execution for a random number of ticks given two possible wait times.'),
    0x7: ('goto', 'H', ['dest'], 'Unconditionally jumps to a specific code block.'),
    0x8: ('imgol', 'HBB', ['image', 'x', 'y'], 'Displays an active image overlay at an animation level higher than the current image overlay at a specified offset position.'),
    0x9: ('imgul', 'HBB', ['image', 'x', 'y'], 'Displays an active image overlay at an animation level lower than the current image overlay at a specified offset position.'),
    0xa: ('imgolorig', 'H', ['image'], 'Displays an active image overlay at an animation level higher than the current image overlay at the relative origin offset position.'),
    0xb: ('switchul', 'H', ['image'], 'Only for powerups. Hypothesised to replace the image overlay that was first created by the current image overlay.'),
    0xc: ('__0c', '', [], 'Unused/invalid opcode; as in, does not exist.'),
    0xd: ('imgoluselo', 'HBB', ['image', 'x', 'y'], 'Displays an active image overlay at an animation level higher than the current image overlay, using a LO* file to determine the offset position.'),
    0xe: ('imguluselo', 'HBB', ['image', 'x', 'y'], 'Displays an active image overlay at an animation level lower than the current image overlay, using a LO* file to determine the offset position.'),
    0xf: ('sprol', 'HBB', ['sprite', 'x', 'y'], 'Spawns a sprite one animation level above the current image overlay at a specific offset position.'),
    0x10: ('highsprol', 'HBB', ['sprite', 'x', 'y'], 'Spawns a sprite at the highest animation level at a specific offset position.'),
    0x11: ('lowsprul', 'HBB', ['sprite', 'x', 'y'], 'Spawns a sprite at the lowest animation level at a specific offset position.'),
    0x12: ('uflunstable', 'H', ['flingy'], 'Creates an flingy with restrictions; supposedly crashes in most cases.'),
    0x13: ('spruluselo', 'HBB', ['sprite', 'x', 'y'], 'Spawns a sprite one animation level below the current image overlay at a specific offset position. The new sprite inherits the direction of the current sprite. Requires LO* file for unknown reason.'),
    0x14: ('sprul', 'HBB', ['sprite', 'x', 'y'], 'Spawns a sprite one animation level below the current image overlay at a specific offset position. The new sprite inherits the direction of the current sprite.'),
    0x15: ('sproluselo', 'HB', ['sprite', 'overlay'], 'Spawns a sprite one animation level above the current image overlay, using a specified LO* file for the offset position information. The new sprite inherits the direction of the current sprite.'),
    0x16: ('end', '', [], 'Destroys the current active image overlay, also removing the current sprite if the image overlay is the last in one in the current sprite.'),
    0x17: ('setflipstate', 'B', ['flipstate'], 'Sets flip state of the current image overlay.'),
    0x18: ('playsnd', 'B', ['sound'], 'Plays a sound.'),
    0x19: ('playsndrand', 'BHH', ['ofsounds', 'sound', 'sound'], 'Plays a random sound from a list.'),
    0x1a: ('playsndbtwn', 'HH', ['sound', 'sound'], 'Plays a random sound between two inclusive sfxdata.dat entry IDs.'),
    0x1b: ('domissiledmg', '', [], 'Causes the damage of a weapon flingy to be applied according to its weapons.dat entry.'),
    0x1c: ('attackmelee', 'BHH', ['ofsounds', 'sound', 'sound'], 'Applies damage to target without creating a flingy and plays a sound.'),
    0x1d: ('followmaingraphic', '', [], 'Causes the current image overlay to display the same frame as the parent image overlay.'),
    0x1e: ('randcondjmp', 'BH', ['chance', 'dest'], 'Random jump, chance of performing jump depends on the parameter.'),
    0x1f: ('turnccwise', 'B', ['amount'], 'Turns the flingy counterclockwise by a particular amount.'),
    0x20: ('turncwise', 'B', ['amount'], 'Turns the flingy clockwise by a particular amount.'),
    0x21: ('turn1cwise', '', [], 'Turns the flingy clockwise by one direction unit.'),
    0x22: ('turnrand', 'B', ['amount'], 'Turns the flingy a specified amount in a random direction, with a heavy bias towards turning clockwise.'),
    0x23: ('setspawnframe', 'B', ['direction'], 'In specific situations, performs a natural rotation to the given direction.'),
    0x24: ('sigorder', 'B', ['signal'], "Allows the current unit's order to proceed if it has paused for an animation to be completed."),
    0x25: ('attackwith', 'B', ['weapontype'], 'Attack with either the ground or air weapon depending on a parameter.'),
    0x26: ('attack', '', [], 'Attack with either the ground or air weapon depending on target.'),
    0x27: ('castspell', '', [], "Identifies when a spell should be cast in a spellcasting animation. The spell is determined by the unit's current order."),
    0x28: ('useweapon', 'B', ['weapon'], 'Makes the unit use a specific weapons.dat ID on its target.'),
    0x29: ('move', 'B', ['pixels'], 'Sets the unit to move forward a certain number of pixels at the end of the current tick.'),
    0x2a: ('gotorepeatattk', '', [], "Signals to StarCraft that after this point, when the unit's cooldown time is over, the repeat attack animation can be called."),
    0x2b: ('engframe', 'B', ['frame'], 'Plays a particular frame, often used in engine glow animations.'),
    0x2c: ('engset', 'B', ['frame'], 'Plays a particular frame set, often used in engine glow animations.'),
    0x2d: ('__2d', '', [], 'Hypothesised to hide the current image overlay until the next animation.'),
    0x2e: ('nobrkcodestart', '', [], 'Holds the processing of player orders until a nobrkcodeend is encountered.'),
    0x2f: ('nobrkcodeend', '', [], 'Allows the processing of player orders after a nobrkcodestart instruction.'),
    0x30: ('ignorerest', '', [], 'Conceptually, this causes the script to stop until the next animation is called.'),
    0x31: ('attkshiftproj', 'B', ['distance'], 'Creates the weapon flingy at a particular distance in front of the unit.'),
    0x32: ('tmprmgraphicstart', '', [], 'Sets the current image overlay state to hidden.'),
    0x33: ('tmprmgraphicend', '', [], 'Sets the current image overlay state to visible.'),
    0x34: ('setfldirect', 'B', ['direction'], 'Sets the current direction of the flingy.'),
    0x35: ('call', 'H', ['dest'], 'Calls a code block.'),
    0x36: ('return', '', [], 'Returns from call.'),
    0x37: ('setflspeed', 'H', ['speed'], 'Sets the flingy.dat speed of the current flingy.'),
    0x38: ('creategasoverlays', 'B', ['overlay'], 'Creates gas image overlays at offsets specified by LO* files.'),
    0x39: ('pwrupcondjmp', 'H', ['dest'], 'Jumps to a code block if the current unit is a powerup and it is currently picked up.'),
    0x3a: ('trgtrangecondjmp', 'HH', ['distance', 'dest'], 'Jumps to a block depending on the distance to the target.'),
    0x3b: ('trgtarccondjmp', 'HHH', ['angle1', 'angle2', 'dest'], 'Jumps to a block depending on the current angle of the target.'),
    0x3c: ('curdirectcondjmp', 'HHH', ['angle1', 'angle2', 'dest'], 'Only for units. Jump to a code block if the current sprite is facing a particular direction.'),
    0x3d: ('imgulnextid', 'BB', ['x', 'y'], 'Displays an active image overlay at the shadow animation level at a specified offset position. The image overlay that will be displayed is the one that is after the current image overlay in images.dat.'),
    0x3e: ('__3e', '', [], 'Unused/invalid opcode; as in, does not exist.'),
    0x3f: ('liftoffcondjmp', 'H', ['dest'], 'Jumps to a code block when the current unit is lifted off.'),
    0x40: ('warpoverlay', 'H', ['frame'], "Hypothesised to display the current image overlay's frame clipped to the outline of the parent image overlay."),
    0x41: ('orderdone', 'B', ['signal'], "Most likely used with orders that continually repeat, like the Medic's healing and the Valkyrie's afterburners (which no longer exist), to clear the sigorder flag to stop the order."),
    0x42: ('grdsprol', 'HBB', ['sprite', 'x', 'y'], 'Spawns a sprite one animation level above the current image overlay at a specific offset position, but only if the current sprite is over ground-passable terrain.'),
    0x43: ('__43', '', [], 'Unused/invalid opcode; as in, does not exist.'),
    0x44: ('dogrddamage', '', [], 'Applies damage like domissiledmg when on ground-unit-passable terrain.'),
}
